@startuml
!theme amiga
title Diagrama de Componentes – Backend

' Módulo Auth
package "AuthModule" {
  [AuthController]         <<Controller>>
  [AuthService]            <<Service>>
  [JwtService]             <<Service>>
  [RecoveryCodeRepository] <<Repository>>
  [UsuarioService]         <<Service>>

  AuthController --> AuthService
  AuthService    --> JwtService
  AuthService    --> RecoveryCodeRepository
  AuthService    --> UsuarioService
}

' Módulo Usuario
package "UsuarioModule" {
  [UsuarioController] <<Controller>>
  [UsuarioService]    <<Service>>
  [UsuarioRepository] <<Repository>>

  UsuarioController --> UsuarioService
  UsuarioService    --> UsuarioRepository
}

' Módulo Categoría
package "CategoriaModule" {
  [CategoriaController] <<Controller>>
  [CategoriaService]    <<Service>>
  [CategoriaRepository] <<Repository>>

  CategoriaController --> CategoriaService
  CategoriaService    --> CategoriaRepository
}

' Módulo Oferta
package "OfertaModule" {
  [OfertaController] <<Controller>>
  [OfertaService]    <<Service>>
  [OfertaRepository] <<Repository>>
  [UsuarioRepository] <<Repository>>
  [CategoriaRepository] <<Repository>>

  OfertaController --> OfertaService
  OfertaService    --> OfertaRepository
  OfertaService    --> UsuarioRepository
  OfertaService    --> CategoriaRepository
}

' Módulo Favorito
package "FavoritoModule" {
  [FavoritoController] <<Controller>>
  [FavoritoService]    <<Service>>
  [FavoritoRepository] <<Repository>>
  [UsuarioRepository]  <<Repository>>
  [OfertaRepository]   <<Repository>>

  FavoritoController --> FavoritoService
  FavoritoService    --> FavoritoRepository
  FavoritoService    --> UsuarioRepository
  FavoritoService    --> OfertaRepository
}



@enduml